<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
echo '</div>'; //* end .site-inner or #inner

do_action( 'genesis_before_footer' );
do_action( 'genesis_footer' );
do_action( 'genesis_after_footer' );

echo '</div>'; //* end .site-container or #wrap

do_action( 'genesis_after' );
wp_footer(); //* we need this for plugins
?>

<script type="text/javascript" src="/wp-content/themes/jemma-theme/jquery-1.11.3.min.js"></script>

<script>
$(window).resize(function(){
    if(document.documentElement.clientWidth <= "769"){
        document.getElementById("menu-main").style.display = "none";
        document.getElementById("nav-mobile-toggle").style.display = "block";
    }else if(document.documentElement.clientWidth > "769"){
        document.getElementById("menu-main").style.display = "block";
        document.getElementById("nav-mobile-toggle").style.display = "none";
    }
})

function showMenu(){
   document.getElementById("menu-main").style.display = "block";
   document.getElementById("m-menu").style.display = "none";
   document.getElementById("m-menu-hide").style.display = "block";
}
function hideMenu(){
    document.getElementById("menu-main").style.display = "none";
    document.getElementById("m-menu-hide").style.display = "none";
      document.getElementById("m-menu").style.display = "block";
}
</script>

</body>
</html>
