<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); //* we need this for plugins
?>


</head>
<?php
genesis_markup( array(
	'html5'   => '<body %s>',
	'xhtml'   => sprintf( '<body class="%s">', implode( ' ', get_body_class() ) ),
	'context' => 'body',
) );
do_action( 'genesis_before' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="wrap">',
	'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
//do_action( 'genesis_header' );
echo '<div id="header">
        <div class="wrap">
              
                    <div class="col-md-12" >
                        <div class="col-md-6" id="silicone-logo">
                          <a href="http://dev.siliconedynamics.net/"><img id="logo-desktop" src="/wp-content/uploads/2015/06/silicone-logo23.png"></a>
                          <center><a href="http://dev.siliconedynamics.net/"><img id="logo-mobile" src="/wp-content/uploads/2015/06/silicone-logo2-mobile.png"></a></center>
                        </div>
                          <div class="col-md-6" id="silicone-phone">
                            <p>
                                Phone: (800) 231-7005<br />
                                Fax: (800) 243-3934<br />
                                <a href="mailto:Sales@SiliconeDynamics.net">Sales@SiliconeDynamics.net</a>
                            </p>
                        </div>
                    </div>
                
        </div>
</div>';
echo "<div class='col-md-12'><div id='nav-mobile-toggle'><div class='wrap'><p id='m-menu' onclick='showMenu();'>Menu</p><p id='m-menu-hide' onclick='hideMenu();'>Menu</p></div></div></div>";
do_action( 'genesis_after_header' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="inner">',
	'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );
